spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: storage

BucketProject:
  filestore: /Users/dylanpion/Desktop/filestore
  app:
    jwtSecret: xhxhh137373uddjshkjqshfkjqhkfhilieufizefhiu
    jwtRefreshSecret: jqhkfhilieufizefhiuxhxhh137373uddjshkjqshfhfkjqhkfhilieufizef
    jwtExpirationMs: 600000
    jwtRefreshExpirationMs: 900000
